name: azure_notification_hubs
description: Flutter support for using Azure Push Notifications in iOS apps.
version: 1.0.2
homepage: https://github.com/Sally-Assistant/azure_notification_hubs.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: aliru.de.azure_notification_hubs
    pluginClass: AzureNotificationHubsPlugin